env:
   global:
      - image="pythonnode_slave"
language: python
python:
  - "2.7"

install:
  - pip install -r example/requirements.txt
  - pip install --pre buildbot_pkg
  - pip install -e .
  - pip install mock

script: trial buildbot_travis/tests

