env:
   global:
      - image=pythonnode_slave
language: python
python:
  - "2.7"
env:
   - TRAVIS_NODE_VERSION="4"
   - TRAVIS_NODE_VERSION="6"
install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - pip install -r example/requirements.txt
  - pip install --pre buildbot_pkg
  - pip install --pre buildbot==0.9.0rc2
  - pip install --pre buildbot-worker==0.9.0rc2
  - pip install -e .
  - pip install mock

script: trial buildbot_travis/tests
after_failure: "cat _trial_temp/test.log"
